## Before submitting
1. Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel\Restart) and then **run all cells** (in the menubar, select Cell\Run All).

2. Make sure that no assertions fail or exceptions occur, otherwise points will be subtracted.\n",

3. After you submit the notebook more tests will be run on your code. The fact that no assertions fail on your computer localy does not guarantee that completed the exercise correctly.

4. Please submit only the `*.ipynb` file.

5. Make sure you fill in any place that says `YOUR CODE HERE` or \"YOUR ANSWER HERE\". Edit only between `YOUR CODE HERE` and `END YOUR CODE`.

6. Make sure to use Python 3.6 at least.

In [78]:
import sys

if sys.version_info < (3, 6):
    print("You are not using a modern enough version of Python. ")

# Exercise Sheet 3: Advanced Numpy

In the third exercise sheet we will work on advanced numpy topics and application on machine learning tasks. You will implement the complete datascience pipline, starting with data loading, plotting and data exploration, and finally implementing a machine learning model and applying it on the data.

For each exercise there will be a maximum number of loops allowed. If your function contains more loops than allowed, you will be notified during the function definition, and the function will automatically fail in the hidden tests. 

For technical reasons the following functions are **banned** throughout the notebook.

- map
- sum
- filter
- np.vectorize
- np.fromiter
- np.fromfunction
- np.apply_along_axis

If you use one of these functions in your submissions it will **automatically fail**.

**Important:** 
   
- Execute every cell in the notebook. You may also try to restart your kernel and execute all cells, in case something went wrong.

In [79]:
# EXECUTE the setup cell !

from typing import Dict, List, Tuple, Optional
from unittest import TestCase

t = TestCase()
from minified import max_allowed_loops, no_imports

from IPython.display import Markdown as md


### Exercise 1.1: ( 8 points ) 

Read the data from the file data.csv and save it in a dictionary. The letters in data.csv are the assigned labels and their corresponding datapoints. Each datapoint is two-dimensional and consists of the given x- and y-values. Return a dictionary with the letters/labels as keys. The value assigned to each key should be a list of x- and y-values. 

* Do not forget to cast the vaules to float.

<!-- * TODO: Is the list allowed to be two dimensional? -->

* Number of loops allowed in this exercise: 1


In [80]:
#@no_imports
#@max_allowed_loops(1)
def read_from_file(file="data.csv"):
    """
    Opens a csv file and parses it line by line. Each line consists of a label and two
    data dimensions. The function returns a dictionary where each key is a label and
    the value is a list of all the datapoints that have that label. Each datapoint
    is represented by a pair (2-element tuple) of floats.

    Args:
        file (str, optional): The path to the file to open and parse. Defaults to
        "data.csv".

    Returns:
        Dict[str, List[Tuple[float, float]]]: The parsed contents of the csv file
    """
    # YOUR CODE HERE
    with open(file, "r") as file:
        dic=dict()
        for line in file:
            print(line)
            (key, val1, val2) = line.split(",")
            val=(float(val1),float(val2))
            #label=line[0]
            if key in dic:
                dic[key].append(val)
            else:
                dic[key]=[val]
                
        return dic
    # YOUR CODE HERE
    
    

In [81]:

tiny_result = read_from_file(file="tiny.csv")
print("tiny_result", tiny_result)
tiny_expected = {"A": [(0.8, 0.9), (0.2, 0.3)], "B": [(0.9, 0.1)], "C": [(2.0, 4.0)]}
t.assertEqual(tiny_result, tiny_expected)

D = read_from_file(file="data.csv")
print(f"Keys of D: {D.keys()}", end="\n\n")
for k, v in D.items():
    print(f"{len(v)} datapoints were assigned the label {k}")

# Test All types
t.assertIsInstance(D, dict)
for d in D:
    t.assertIsInstance(d, str)
    t.assertIsInstance(D[d], list)
    for el in D[d]:
        t.assertIsInstance(el, tuple)
        t.assertIsInstance(el[0], float)
        t.assertIsInstance(el[1], float)

letters = "MNU"
t.assertEqual(set(D.keys()), set(letters))
t.assertTrue(all(len(v) > 99 for v in D.values()))

A,0.8,0.9

A,0.2,0.3

B,0.9,0.1

C,2,4
tiny_result {'A': [(0.8, 0.9), (0.2, 0.3)], 'B': [(0.9, 0.1)], 'C': [(2.0, 4.0)]}
N,1.68,1.213

N,-0.321,-1.458

M,1.027,-2.626

N,2.636,4.068

N,1.395,0.52

N,0.38,4.078

N,4.069,5.29

N,-0.501,0.336

M,-0.579,-2.471

M,-1.644,0.726

U,8.331,9.42

M,-1.905,-0.149

N,0.602,2.601

N,-0.864,1.622

M,-3.697,-0.614

N,3.167,-0.404

N,1.737,1.917

N,3.405,0.169

M,-0.726,-2.393

N,1.362,-3.626

U,7.424,7.519

U,5.166,6.231

M,-2.085,3.252

M,2.052,-0.007

M,-2.046,-2.531

U,7.5,7.066

U,7.909,7.614

N,-2.214,0.524

U,7.22,5.588

M,0.496,-0.08

M,-1.818,-0.161

M,1.767,-1.75

N,1.491,1.174

N,0.876,-1.269

U,8.568,6.737

M,-3.521,0.494

U,5.859,5.217

U,4.768,8.359

U,4.846,7.808

N,1.122,1.617

N,2.304,1.295

N,-1.308,-1.68

U,7.171,4.946

N,-0.729,4.233

N,6.234,-1.67

N,0.714,2.631

U,11.533,8.008

U,11.0,5.779

N,0.044,1.147

M,-0.527,-1.549

U,7.589,8.271

U,5.634,6.727

N,1.711,0.108

M,-2.602,-1.622

M,0.963,-1.764

M,1.181,-2.97

N,-1.846,0.631


### Exercise 1.2: ( 5 Pts )

Use numpy to stack all of the $N$ datapoints from the dictionary into one matrix $X$, containing the data.

Additionally, create one array $y$ with the corresponding integer labels. 

Each datapoint $x_i \in X, \> i = \overline{1..N}$ is of dimension $D=2$. The label assigned to a datapoint has to be a positive integer. Every letter-label should map to one integer-label in $y$ accordingly.

Maping example: $A \rightarrow 0,\> C \rightarrow 1,\> K \rightarrow 2, ...$ (The order of the keys/labels defines the numeric label. The first key is mapped to 0 and so on.)

* Dataset $X$: $$\Large X \in \mathbb{R}^{(N, D)}$$
* Labels $y$: $$\Large y \in \mathbb{N}^{(N,)} $$

* Number of loops allowed in this exercise: 1 (for iterating over the keys of the dictionary)

In [82]:
import numpy as np


In [83]:
@no_imports
@max_allowed_loops(1)
def stack_data(
    D: Dict[str, List[Tuple[float, float]]]
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Convert a dictionary dataset into a two arrays of data and labels. The dictionary 
    keys represent the labels and the value mapped to each key is a list that 
    contains all the datapoints belonging to that label. The output are two arrays 
    the first is the datapoints in a single 2d array and a vector of intergers 
    with the coresponding label for each datapoint. The order of the datapoints is
    preserved according to the order in the dictionary and the lists.

    The labels are converted from a string to a unique int.
    
    The datapoints are entered in the same order as the keys in the `D`. First
    all the datapoints of the first key are entered then the second and so on.
    Within one label order also remains.
    
    Args:
        D (Dict[str, List[Tuple[float, float]]]): The dictionary that should be stacked

    Returns:
        Tuple[np.ndarray, np.ndarray]: The two output arrays. The first is a 
        float-matrix containing all the datapoints. The second is an int-vector 
        containing the labels for each datapoint
    """

    # YOUR CODE HERE
    #dict: tiny_result {'A': [(0.8, 0.9), (0.2, 0.3)], 'B': [(0.9, 0.1)], 'C': [(2.0, 4.0)]}

    
    # YOUR CODE HERE
    
    return X, y

In [84]:
tiny_expected_X, tiny_expected_y = (
    np.array([[0.0, 0.1], [0.9, 0.7], [0.8, 0.3],]),
    np.array([0, 1, 1]),
)
tiny_result_X, tiny_result_y = stack_data(
    {"B": [(0.0, 0.1)], "A": [(0.9, 0.7), (0.8, 0.3)]}
)
print(tiny_result_X, tiny_result_y)
np.testing.assert_allclose(tiny_expected_X, tiny_result_X)
np.testing.assert_allclose(tiny_expected_y, tiny_result_y)

X, y = stack_data(D)
print(X.shape, y.shape)
print(X.dtype, y.dtype)

expected_len = sum(len(x) for x in D.values())
print(f"Expected length for X, y: {expected_len}")

t.assertEqual(X.shape, (expected_len, 2))
t.assertEqual(y.shape, (expected_len,))

t.assertEqual(X.dtype, np.float64)
t.assertEqual(y.dtype, np.int64)

t.assertEqual(set(y), set(range(len(D))))


NameError: name 'X' is not defined

### Exercise 1.3: ( 4 Pts )

Write a function that returns a list of all $k$ clusters $C$. A cluster $C_k$ is composed of every datapoint $X_i$ assigned with the label $k$. There are as many clusters $C_k$ as there are unique labels in $y$.


$$\Large{\mathcal{C} = \{ C_1, C_2, \cdots, C_k \},\quad k = \overline{1..K}}$$

<br>

$$\Large C_k \in \mathbb{R}^{(N_k, D)}$$

* Number of loops allowed in this exercise: 1

In [87]:
@no_imports
@max_allowed_loops(1)
def get_clusters(X, y):
    """
    Receives a labeled dataset and splits the datapoints according to label

    Args:
        X (np.ndarray): The dataset
        y (np.ndarray): The label for each point in the dataset

    Returns:
        List[np.ndarray]: A list of arrays where the elements of each array
        are datapoints belonging to the label at that index.
        
    Example:
    >>> get_clusters(
            np.array([[0.8, 0.7], [0, 0.4], [0.3, 0.1]]), 
            np.array([0,1,0])
        )
    >>> [array([[0.8, 0.7],[0.3, 0.1]]), 
         array([[0. , 0.4]])]
    """
    # YOUR CODE HERE
    indices1=np.argwhere(y==1).flatten()
    indices0=np.argwhere(y==0).flatten()
    print(indices0)
    return (X[[indices0]],X[[indices1]])
    # YOUR CODE HERE
    

In [88]:
tiny_result = get_clusters(
    np.array([[0.8, 0.7], [0, 0.4], [0.3, 0.1]]), np.array([0, 1, 0])
)
print(tiny_result)
tiny_expected = [np.array([[0.8, 0.7], [0.3, 0.1]]), np.array([[0.0, 0.4]])]
for r, e in zip(tiny_result, tiny_expected):
    np.testing.assert_allclose(r, e)

clusters = get_clusters(X, y)
# output is list
t.assertIsInstance(clusters, List)
t.assertEqual(len(letters), len(clusters))

# all elements are arrays
for el in clusters:
    t.assertIsInstance(el, np.ndarray)

t.assertEqual(sum(map(len, clusters)), len(X))


[0 2]
(array([[ 0.8,  0.7],
       [ 0.3,  0.1]]), array([[ 0. ,  0.4]]))


NameError: name 'X' is not defined

### Exercise 1.4: ( 8 Pts )

Split the data $X$ into training and testing data.

* Return a list of clusters for training and a list of cluster for testing.


* Utilize the function __train_test_idxs(L, test_ratio)__ from utils to split the data.

- The train-test ratio should be 80-20

* Use the function implemented in Exercise 1.3 __get_clusters(X,y)__ to get the clusters.


* Number of loops allowed in this exercise: 0

In [90]:
from utils import train_test_idxs

print("train_test_idxs specification:\n", train_test_idxs.__doc__)

train_test_idxs specification:
 
    Returns indices that can be used as train and test data.

    Args:
        L (int): The size of the dataset
        test_ratio (float): The ratio [0-1] of indices that should be put in the test
        set

    Returns:
        Tuple[np.ndarray, np.ndarray]: The training and testset indices
    


In [91]:
@no_imports
@max_allowed_loops(0)

def split(X: np.ndarray, y: np.ndarray) -> Tuple[List[np.ndarray], List[np.ndarray]]:
    """
    Split the data into train and test sets. The training and test set are clustered by
    label using `get_clusters`. The size of the training set is 80% of the whole
    dataset
    
    Args:
        X (np.ndarray): The dataset (2d)
        y (np.ndarray): The labels (1d)

    Returns:
        Tuple[List[np.ndarray], List[np.ndarray]]: The clustered training and 
        testset
    """
    # YOUR CODE HERE
    L=X.shape[0]
    test_ratio=0.8
    indices_tr=train_test_idxs(L,test_ratio) #The training and testset indices
    indices_te=np.setdiff1d(np.arange(L),indices_Tr)
    tr=X[indices_tr]
    te=X[indices_te]
    
    tr_clusters=get_clusters(tr,y[indices_tr]) #array with data labeled 0, array with data labeled 1
    te_clusters=get_clusters(te,y[indices_te])
    
    #Return a list of clusters for training and a list of cluster for testing.

    # YOUR CODE HERE
    

    return tr_clusters, te_clusters

In [92]:
output = split(X, y)
tr_clusters, te_clusters = output
t.assertIsInstance(output, Tuple)
t.assertIsInstance(tr_clusters, List)
t.assertIsInstance(te_clusters, List)

t.assertEqual(len(tr_clusters), len(te_clusters))
t.assertEqual(len(tr_clusters), len(letters))
t.assertEqual(len(te_clusters), len(letters))

for el in tr_clusters + te_clusters:
    t.assertIsInstance(el, np.ndarray)


n_in_train = sum(map(len, tr_clusters))
n_in_test = sum(map(len, te_clusters))
t.assertEqual(n_in_train + n_in_test, len(X))

percent_train = n_in_train / len(X)
t.assertGreaterEqual(percent_train, 0.78)
t.assertLessEqual(percent_train, 0.82)


NameError: name 'X' is not defined

### Exercise 1.5:  (5 Pts )

Compute the mean $\mu_k$ of each cluster $C_k$. Return a list of all cluster means $\mu$.


$$\Large{\mu = \{ \mu_1, \mu_2, \cdots, \mu_k \},\quad k = \overline{1..K}}$$



* Number of elements in a cluster $k$:
$$\Large{N_k = | C_k |, \quad C_k \in \mathbb{R}^{(N_k, D)}}$$



* The $k$-th cluster mean $\mu_k$:
$$\Large{ \mu_k = \frac{1}{N_k}\sum_{x_i \in C_k} x_i }$$



* Number of loops allowed in this exercise: 1 (to iterate over the clusters)

In [93]:
@no_imports
@max_allowed_loops(1)
def calc_means(clusters: List[np.ndarray]) -> np.ndarray:
    """
    For a collections of clusters calculate the mean for each cluster
    
    Args:
        clusters (List[np.ndarray]): A list of 2d arrays
        
    Returns:
        List[np.ndarray]: A matrix where each row represents a mean of a cluster
        
    Example: 
        >>> tiny_clusters = [
            np.array([[0.2, 0.3], [0.1, 0.2]]),
            np.array([[0.8, 0.9], [0.7, 0.5], [0.6, 0.7]]),
        ]
        >>> calc_means(tiny_clusters)
        [array([0.15, 0.25]), array([0.7,0.7])]
    """
    # YOUR CODE HERE
    means=[]
    for cluster in clusters:
        means.append(cluster.mean(axis=0))
    return means
    # YOUR CODE HERE
    

In [94]:
tiny_clusters = [
    np.array([[0.2, 0.3], [0.1, 0.2]]),
    np.array([[0.8, 0.9], [0.7, 0.5], [0.6, 0.7]]),
]
tiny_result = calc_means(tiny_clusters)
print(tiny_result, end="\n\n")
tiny_expected = np.array([[0.15, 0.25], [0.7, 0.7]])
np.testing.assert_allclose(tiny_result, tiny_expected)

means = calc_means(tr_clusters)
print(means)
t.assertIsInstance(means, np.ndarray)
t.assertEqual(means.shape, (len(letters), 2))


[array([ 0.15,  0.25]), array([ 0.7,  0.7])]



NameError: name 'tr_clusters' is not defined

### Exercise 2.1: Scatter plot of clusters ( 15 points )

- Create a scatter plot of size 8x8. 

- Plot each datapoint of a cluster $x_{ik} \in  C_k$ as dots with an alpha value of 0.6 and a label. 

- The plot-label should contain both the cluster's letter-label as well as its integer-label. 

- Further, plot the cluster's mean $\mu_k$ as a red cross of size 7. The plot should also have a label for each cluster's mean, giving information on its exact coordinates. 

- The title of the plot should be _'Scatter plot of the clusters'_ in fontsize 20.

* Label for the scatter plots example: _A = 0_
* Label for the cluster means example (use LaTeX): _$\mu_A:$[1.23  0.56]_

- If the mean of each cluster is not provided, use `calc_means(clusters)` to calculate the means.


* Number of loops allowed in this exercise: 1 (for iteration over the clusters)


In [ ]:
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
@no_imports
def plot_scatter_and_mean(
    clusters: List[np.ndarray],
    letters: List[str],
    means: Optional[List[np.ndarray]] = None,
) -> None:
    """
    Create a scatter plot visulizing each cluster and its mean
    
    Args:
        clusters (List[np.ndarray]): A list containing arrrays representing 
        each cluster
        letters (List[str]): The "name" of each cluster
        means (Optional[List[np.ndarray]]): The mean of each cluster. If not
        provided the mean of each cluster in `clusters` should be calculated and 
        used
        
    """
    assert len(letters) == len(clusters)

    # YOUR CODE HERE
    raise NotImplementedError("Relplace this line with your code")
    # YOUR CODE HERE
    

In [ ]:
plot_scatter_and_mean(tr_clusters, letters, means=None)

### Exercise 2.2: (15 points)

 - To make it easier to visually analyse the the differences between clusters, the data can be projected onto an axis. Plot a histrogram for the projection onto the given axis. 
 
 - The histogram should have 30 bins, be 50% transparent and labeled. The area under the histogram should be normalized and sum to 1 to represent a proper distribution. It can be done by setting the corresponding parameter.  - The bars width should have 4/5 of the bins width.


- Create a scatter plot of size 14x5.
* Plot the mean of each cluster as a vertical, dashed, red line.
* Label for the histograms example: _A_
* The title of the plot should be dynamic, have a font size of 20 and explain the axis of the projection, e.g. "Projection to axis 0 histogramm plot" or "Projection to axis 1 histogramm plot", depending on the axis.


* Number of loops allowed in this exercise: 1 (to iterate over the clusters)

In [ ]:
@no_imports
def plot_projection(
    clusters: List[np.ndarray], letters: List[str], means: np.ndarray, axis: int = 0
):
    """
    Plot a histogram of the dimension provided in `axis`
    
    Args:
        clusters (List[np.ndarray]): The clusters from which to create the historgram
        letters (List[str]): The string representation of each class
        means (np.ndarray): The mean of each class
        axis (int): The axis from which to create the historgram. Defaults to 0.
    """
    # YOUR CODE HERE
    
    # YOUR CODE HERE
    

In [ ]:
plot_projection(tr_clusters, letters, means, axis=0)

### Exercise 3.1: (8 points)

Compute the within cluster covariance $S_w$ to further analyse the distribution of the data in the clusters. Sum up the covariance matrices of each cluster to get the one average within cluster corvariance matrix. **This is shown in the formula below.** Covariance matrices describe the relationship between the x and y dimensions of the data.

$$\boxed{\Large{S_w  = \sum_{k=1}^K \sum_{x_i \in C_k} (x_i - \mu_k) (x_i - \mu_k)^{\top}}, \quad S_w \in \mathbb{R}^{(D, D)}}$$


* Reminder: Data $C$ is a set of clusters $C_k$, where $K$ is the total number of clusters. $${\mathcal{C} = \{ C_1, C_2, \cdots, C_k \},\quad k = \overline{1..K}}$$

* Number of elements in a cluster $k$: $${N_k = | C_k |, \quad C_k \in \mathbb{R}^{(N_k, D)}}$$
<br>

* $k$-th cluster mean $\mu_k$: $${ \mu_k = \frac{1}{N_k}\sum_{x_i \in C_k} x_i }$$

* Number of loops allowed in this exercise: 1 (to iterate over the clusters)

In [97]:
@no_imports
@max_allowed_loops(1)
def within_cluster_cov(clusters: List[np.ndarray]) -> np.ndarray:
    """
    Calculate the within class covariance for a collection of clusters
    
    Args:
        clusters (List[np.ndarray]): A list of clusters each consisting of 
        an array of datapoints
        
    Returns:
        np.ndarray: The within cluster covariance 
        
    Example: 
        >>> within_cluster_cov(
            [array([[0.2, 0.3], [0.1, 0.2]]), array([[0.8, 0.9], [0.7, 0.5], [0.6, 0.7]])]
        )
        >>> array([[0.025, 0.025],
                   [0.025, 0.085]])
    """
    d = clusters[0].shape[1]
    S_w = np.zeros((d, d))
    # YOUR CODE HERE
    for clu in clusters:
        Nk=clu.shape[0]
        l=(clu.sum(axis=0))/Nk
        m=clu-l
        z=m[None]*m[None].T
        z=z.transpose(1,0,2)
        z=np.sum(z,axis=0)
        S_w+=z
    return S_w
        
    # YOUR CODE HERE
    

In [98]:
tiny_clusters = [
    np.array([[0.2, 0.3], [0.1, 0.2]]),
    np.array([[0.8, 0.9], [0.7, 0.5], [0.6, 0.7]]),
]
tiny_expected = np.array([[0.025, 0.025], [0.025, 0.085]])
tiny_result = within_cluster_cov(tiny_clusters)
print(tiny_result)
np.testing.assert_allclose(tiny_expected, tiny_result)

S_w = within_cluster_cov(tr_clusters)
print(S_w)
t.assertIsInstance(S_w, np.ndarray)
t.assertEqual(S_w.shape, (2, 2))

# check if symmetric
np.testing.assert_allclose(S_w, S_w.T)


[[ 0.025  0.025]
 [ 0.025  0.085]]


NameError: name 'tr_clusters' is not defined

### Exercise 3.2: ( 3 + 9 points )

To compute the between cluster covariance, the calculation of the mean of means is necessary. In the function `calc_mean_of_means(clusters)` you must reuse your function `calc_means(clusters)`.


* Mean of means: $$\Large{ \mu = \frac{1}{N}\sum_{C_i \in \mathcal{C}}{C_i}},\quad \text{where}\quad N = |\mathcal{C}|$$


The between cluster covariance describes the relation of the datapoints from one cluster to the other. It focuses on the differences rather then the similarities. Use the function `calc_mean_of_means(clusters)` in the function `between_cluster_cov(clusters)` to access the mean of means. **You only have to implement the given formulas**, and do not need to fully understand the underlying concept. 

* Between cluster covariance: $$\boxed{\Large{S_b = \sum_{k=1}^K  N_k (\mu_k - \mu) (\mu_k - \mu)^{\top}}}$$


* Number of loops allowed in this exercise: 0 + 1 (one loop only in `between_cluster_cov(clusters)`, to iterate over the clusters)

In [99]:
@no_imports
@max_allowed_loops(0)
def calc_mean_of_means(clusters: List[np.ndarray]) -> np.ndarray:
    """
    Given a collection of datapoints divided in clusters, calculate the 
    mean of all cluster means.
    Args:
        clusters (List[np.ndarray]): A list of clusters represented in arrays
        
    Returns:
        np.ndarray: A single datapoint that represents the mean of all the
        cluster means
        
    Example:
        >>> calc_mean_of_means(
                [np.array([[0.222, 0.333], [0.1, 0.2]]), np.array([[0.8, 0.9], [0.7, 0.5], [0.6, 0.7]])]
            )
        >>> array([0.4305 , 0.48325])
    """
    # YOUR CODE HERE
    listofarrays=calc_means(clusters)
    return np.array(listofarrays).mean(axis=0)
    # YOUR CODE HERE
    

In [100]:
tiny_result = calc_mean_of_means(
    [
        np.array([[0.222, 0.333], [0.1, 0.2]]),
        np.array([[0.8, 0.9], [0.7, 0.5], [0.6, 0.7]]),
    ]
)
print(tiny_result)
tiny_expected = np.array([0.4305, 0.48325])
np.testing.assert_allclose(tiny_expected, tiny_result)

mean_of_means = calc_mean_of_means(tr_clusters)
print(mean_of_means)
t.assertIsInstance(mean_of_means, np.ndarray)
t.assertEqual(mean_of_means.shape, (2,))


[ 0.4305   0.48325]


NameError: name 'tr_clusters' is not defined

In [126]:
@no_imports
@max_allowed_loops(1)
def between_cluster_cov(
    clusters: List[np.ndarray], cluster_means: List[np.ndarray], mean_of_means: np.ndarray
) -> np.ndarray:
    """
    Calculate the covariance between clusters.
    
    Args:
        clusters (List[np.ndarray]): A list of datapoints divided by cluster
        cluster_means (List[np.ndarray]): A list of vectors representing the mean
        of each cluster
        mean_of_means (np.ndarray): A vector, the mean of all datapoints
    
    Returns:
        np.ndarray: Covariance between clusters
        
    Example: 
        >>> tiny_clusters = [
            np.array([[0.2, 0.3], [0.1, 0.2]]),
            np.array([[0.8, 0.9], [0.7, 0.5], [0.6, 0.7]]),
        ]
        >>> tiny_means = [np.array([0.15, 0.25]), np.array([0.7, 0.7])]
        >>> tiny_mean_of_means = np.array([0.425, 0.475])
        >>> between_cluster_cov(tiny_clusters, tiny_means, tiny_mean_of_means)
        array([[0.378125, 0.309375],
               [0.309375, 0.253125]])
        
    """
    d = clusters[0].shape[1]
    S_b = np.zeros((d, d))
    l= mean_of_means
    # YOUR CODE HERE
    for i,clu in enumerate(clusters):
        Nk=clu.shape[0]
        lk=cluster_means[i]
        S_b+=Nk*(lk-l)[None]*(lk-l)[None].T
        print((lk-l)[None]*(lk-l)[None].T)
    return S_b
    # YOUR CODE HERE
    

In [127]:
tiny_clusters = [
    np.array([[0.2, 0.3], [0.1, 0.2]]),
    np.array([[0.8, 0.9], [0.7, 0.5], [0.6, 0.7]]),
]
tiny_means = [np.array([0.15, 0.25]), np.array([0.7, 0.7])]
tiny_mean_of_means = np.array([0.425, 0.475])
between_cluster_cov(tiny_clusters, tiny_means, tiny_mean_of_means)

S_b = between_cluster_cov(tr_clusters, means, mean_of_means)
print(S_b)
t.assertIsInstance(S_b, np.ndarray)
t.assertEqual(S_b.shape, (2, 2))
np.testing.assert_allclose(S_b, S_b.T)


[[ 0.075625  0.061875]
 [ 0.061875  0.050625]]
[[ 0.075625  0.061875]
 [ 0.061875  0.050625]]


NameError: name 'tr_clusters' is not defined

In [128]:
m=between_cluster_cov(tiny_clusters, tiny_means, tiny_mean_of_means)
print(m)
#array([[0.378125, 0.309375],
#       [0.309375, 0.253125]]

[[ 0.075625  0.061875]
 [ 0.061875  0.050625]]
[[ 0.075625  0.061875]
 [ 0.061875  0.050625]]
[[ 0.378125  0.309375]
 [ 0.309375  0.253125]]


### Exercise 3.3 (14 points):

Compute rotation matrix $W$. To find the rotation matrix you first need to find a matrix $A$ so that the within cluster covariance matrix can be transformed into the between cluster covariance matrix. 

$$\Large{ S_w A = S_b}$$

Next, find the eigenvalues of this matrix $A$. The eigenvectors describe the direction in which the matrix $A$ does _not_ transform and instead only scales. These vectors form the rotation matrix, as they show the directions in which the difference between $S_w$ and $S_b$ is maximized. **Implement the given formulas!**

$$ \Large{AW = \lambda W}$$
* Return the rotation matrix and the index of its biggest axis.


* Number of loops allowed in this exercise: 0

In [133]:
@no_imports
@max_allowed_loops(0)
def rotation_matrix(S_w: np.ndarray, S_b: np.ndarray) -> Tuple[np.ndarray, int]:
    """
    Calculate the transformation matrix given the within- and between cluster
    covariance matrices.
    
    Args:
        S_w (np.ndarray): The within cluster covariance
        S_b (np.ndarray): The between cluster covariance
    
    Returns:
        np.ndarray: The transformation matrix
        int: The axis along with the transformed data achieves maximal variance
        
    Example:
        >>> tiny_S_w = np.array([[0.025, 0.025], [0.025, 0.085]])
        >>> tiny_S_b = np.array([[0.378125, 0.309375], [0.309375, 0.253125]])
        >>> rotation_matrix(tiny_S_w, tiny_S_b)
        (array([[ 0.99752952, -0.63323779],
                [-0.07024856,  0.7739573 ]]), 0)
    """
    # YOUR CODE HERE
    A=np.linalg.inv(S_w)@S_b
    W=np.linalg.eig(A)[1]
    big_axis=A.shape.index(max(A.shape))
    return (W,big_axis)
    # YOUR CODE HERE
    

In [134]:
tiny_S_w = np.array([[0.025, 0.025], [0.025, 0.085]])
tiny_S_b = np.array([[0.378125, 0.309375], [0.309375, 0.253125]])
tiny_result_M, tiny_result_max_axis = rotation_matrix(tiny_S_w, tiny_S_b)
print(tiny_result_M, tiny_result_max_axis)
tiny_expected_M, tiny_expected_max_axis = (
    np.array([[0.99752952, -0.63323779], [-0.07024856, 0.7739573]]),
    0,
)
np.testing.assert_allclose(tiny_expected_M, tiny_result_M)
np.testing.assert_allclose(tiny_expected_max_axis, tiny_result_max_axis)

output = rotation_matrix(S_w, S_b)
t.assertIsInstance(output, Tuple)
t.assertEqual(len(output), 2)
W_rot, max_axis = output
t.assertIsInstance(W_rot, np.ndarray)
t.assertIsInstance(max_axis, np.int64)
t.assertEqual(W_rot.shape, (2, 2))


[[ 0.99752952 -0.63323779]
 [-0.07024856  0.7739573 ]] 0


NameError: name 'S_w' is not defined

### Exercise 3.4: (6  points)

Apply rotation matrix to the clusters and return the rotated clusters in a list. 

* Number of loops allowed in this exercise: 1 (to iterate over the clusters)

In [135]:
@no_imports
@max_allowed_loops(1)
def rotate_clusters(W_rot: np.ndarray, clusters: List[np.ndarray]) -> List[np.ndarray]:
    """
    Rotate all the datapoints in all the clusters
    
    Args:
        W_rot (np.ndarray): The rotation matrix
        clusters (List[np.ndarray]): The list of datapoints divided in clusters that 
        will be rotated
        
    Returns: 
        List[np.ndarray]: The rotated datapoints divided by cluster
    """
    # YOUR CODE HERE
    rot=[]
    for clu in clusters:
        data_rot=clu@W_rot
        rot.append(data_rot)
    return rot
    # YOUR CODE HERE
    

In [136]:
rad = np.deg2rad(30)
c, s = np.cos(rad), np.sin(rad)
rot30 = np.array([[c, -s], [s, c]])
tiny_clusters = [
    np.array([[0.2, 0.3], [0.1, 0.2]]),
    np.array([[0.8, 0.9], [0.7, 0.5], [0.6, 0.7]]),
]
tiny_rotated_result = rotate_clusters(rot30, tiny_clusters)
print(tiny_rotated_result)
tiny_rotated_expected = [
    np.array([[0.32320508, 0.15980762], [0.18660254, 0.12320508]]),
    np.array(
        [[1.14282032, 0.37942286], [0.85621778, 0.0830127], [0.86961524, 0.30621778]]
    ),
]
for r, e in zip(tiny_rotated_result, tiny_rotated_expected):
    np.testing.assert_allclose(r, e)
    
rot_tr_clusters = rotate_clusters(W_rot, tr_clusters)
t.assertIsInstance(rot_tr_clusters, List)
for norm, rotated in zip(tr_clusters, rot_tr_clusters):
    t.assertIsInstance(rotated, np.ndarray)
    t.assertEqual(norm.shape, rotated.shape)


[array([[ 0.32320508,  0.15980762],
       [ 0.18660254,  0.12320508]]), array([[ 1.14282032,  0.37942286],
       [ 0.85621778,  0.0830127 ],
       [ 0.86961524,  0.30621778]])]


NameError: name 'W_rot' is not defined

### Goal

Using the rotated clusters, we can now plot the clusters projected onto the axis with highest eigenvalue as histograms. Here we can draw a more accurate line separating the clusters than we could before. This line can be used for classifying data through drawing a simple line between clusters.

In [ ]:
plot_scatter_and_mean(rot_tr_clusters, letters)
means = calc_means(rot_tr_clusters)
means
plot_projection(rot_tr_clusters, letters, means, axis=max_axis)